---
resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/Ashreesee/AI.git
      branch: main

jobs:
  - name: build-and-test
    plan:
      - get: source-code
        trigger: true

      - task: install-dependencies
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: "18"

          inputs:
            - name: source-code

          outputs:
            - name: source-code

          run:
            path: sh
            args:
              - -exc
              - |
                cd source-code
                npm install


      - task: build-app
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: node
              tag: "18"

          inputs:
            - name: source-code

          outputs:
            - name: build-output  # Store built files

          run:
            path: sh
            args:
              - -exc
              - |
                cd source-code
                npm run build
                cp -r build ../build-output