---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: "18"

inputs:
  - name: AI

outputs:
  - name: build-output  # Save build artifacts

run:
  path: sh
  args:
    - -exc
    - |
      cd AI
      npm run build
      cp -r build ../build-output
