---
platform: linux
image_resource:
  type: docker-image
  source: { repository: docker, tag: latest }

inputs:
  - name: react-app-repo

params:
  DOCKERHUB_USERNAME: "ashreesee"
  DOCKERHUB_PASSWORD: "^kyYjiNR82ihur%"
  IMAGE_NAME: "my-react-app"

run:
  path: sh
  args:
    - -exc
    - |
      cd react-app-repo
      echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      docker build -t $IMAGE_NAME .
      docker push $IMAGE_NAME
