---
platform: linux
image_resource:
  type: docker-image
  source: { repository: node, tag: '18' }

inputs:
  - name: react-app-repo

outputs:
  - name: build-artifacts

run:
  path: sh
  args:
    - -ec
    - |
      echo "Building React app..."
      cd react-app-repo
      npm install
      npm run build
      echo "Moving build artifacts..."
      mkdir -p ../build-artifacts
      mv build ../build-artifacts/
      echo "Build process completed successfully."
