---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: "18"

inputs:
  - name: AI  # Cloned repo

outputs:
  - name: AI  # Persist changes

run:
  path: sh
  args:
    - -exc
    - |
      cd AI
      npm install
