---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: "18"

inputs:
  - name: AI

run:
  path: sh
  args:
    - -exc
    - |
      cd AI
      npm test -- --ci --coverage
